version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: nestjs-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:0000@localhost:5432/demodb?schema=public
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "5173"
    depends_on:
      - backend

  database:
    image: postgres:15
    container_name: postgres-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: demodb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: